# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:mariadb://localhost:3306/taskdb
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=bde0234f91656e466371fa59609be3fb
app.jwt.expiration-ms=3600000

# Logging
logging.level.root=INFO
logging.level.com.example=DEBUG
